name: Cloudflare Purge Cache Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Cache Purge Action
        uses: NathanVaughn/actions-cloudflare-purge@v2.0.0
        if: success()
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
