name: "Cloudflare Purge Cache"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloudflare Purge Cache
      - uses: jakejarvis/cloudflare-purge-action@v0.3.
        env:
            CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
            CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
            
